DROP DATABASE IF EXISTS MOREDDL
create database if not exists MOREDDL;
use MOREDDL;
#Name: Charles Pink
#Date: 10/22/2019
#Class: Data Fundamentals


drop table if exists EMPLOYEE_PROJECT;
drop table if exists PROJECT;
drop table if exists EMPLOYEE;
drop table if exists PROJECT_CATEGORY;

create table PROJECT_CATEGORY(
    CATEGORY_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50) NOT NULL
);

create table EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE,
    HIRE_DATE DATETIME
);

create table PROJECT(
    PROJECT_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PROJECT_NAME VARCHAR(50) NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    BUDGET DECIMAL, CHECK ( BUDGET <= 99999.99 ),
    CATEGORY_ID INTEGER NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES PROJECT_CATEGORY(CATEGORY_ID)
);

create table EMPLOYEE_PROJECT(
    EMPLOYEE_PROJECT_ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PROJECT_ID INTEGER NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL,
    PROJECT_LEAD BIT DEFAULT 0,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


