#create database Products_DD;
use Products_DD;
#Name: Charles Pink
#Date: 10/22/2019
#Class: Data Fundamentals

#I need to create tables in this order so later I can put in f_keys correctly
#In this order Supplier, Product, Clothing Category, Clothing Size, Colour, Product Category,
#Product Size, Product Colour
ALTER TABLE Supplier ADD CONSTRAINT PK_SupplierID PRIMARY KEY (SupplierID);
ALTER TABLE Supplier MODIFY SupplierID int auto_increment;
ALTER TABLE Supplier MODIFY SupplierName varchar(100) NOT NULL;
ALTER TABLE Supplier MODIFY Address VARBINARY(255) NOT NULL;
ALTER TABLE Supplier MODIFY IsActive BIT NOT NULL;
ALTER TABLE Supplier MODIFY IsActive BIT DEFAULT 1;


ALTER TABLE PRODUCT ADD CONSTRAINT PK_ProductID PRIMARY KEY (ProductID);
ALTER TABLE PRODUCT MODIFY ProductID integer auto_increment;
ALTER TABLE PRODUCT MODIFY ProductCode integer NOT NULL;
ALTER TABLE PRODUCT ADD CONSTRAINT UN_ProductCode UNIQUE (ProductCode);
ALTER TABLE PRODUCT MODIFY ProductName char (8) NOT NULL;
ALTER TABLE PRODUCT MODIFY RetailPrice VARCHAR(100) NOT NULL;
ALTER TABLE PRODUCT ADD CONSTRAINT CK_RetailPrice CHECK (RetailPrice < 0 );
ALTER TABLE PRODUCT MODIFY ProductRating int (3) NOT NULL;
ALTER TABLE PRODUCT ADD CONSTRAINT CK_SalePrice CHECK (SalePrice < 0 );
ALTER TABLE PRODUCT ADD CONSTRAINT CK_ProductRating CHECK (  ProductRating >= 1 AND ProductRating <= 5 );
ALTER TABLE PRODUCT MODIFY NumberInStock VARCHAR (100) NOT NULL ;
ALTER TABLE PRODUCT MODIFY NumberInStock VARCHAR(100) DEFAULT 0;
ALTER TABLE PRODUCT MODIFY IsActive BIT NOT NULL;
ALTER TABLE PRODUCT MODIFY IsActive BIT DEFAULT 0;
ALTER TABLE PRODUCT MODIFY IsDiscontinued BIT NOT NULL;
ALTER TABLE PRODUCT MODIFY IsDiscontinued BIT DEFAULT 1;

ALTER TABLE CLOTHINGCATEGORY ADD CONSTRAINT PK_CategoryID PRIMARY KEY (CategoryID);
ALTER TABLE CLOTHINGCATEGORY MODIFY CategoryID INTEGER AUTO_INCREMENT;
ALTER TABLE CLOTHINGCATEGORY MODIFY IsActive BIT NOT NULL;
ALTER TABLE CLOTHINGCATEGORY MODIFY IsActive BIT DEFAULT 1;


ALTER TABLE CLOTHINGSIZE ADD CONSTRAINT PK_CLOTHINGSIZE PRIMARY KEY (SizeID);
ALTER TABLE CLOTHINGSIZE MODIFY SizeID INTEGER AUTO_INCREMENT;
ALTER TABLE CLOTHINGSIZE MODIFY SizeName VARCHAR(50) NOT NULL;
ALTER TABLE CLOTHINGSIZE MODIFY SizeAbbreviation VARCHAR(3) NOT NULL;
ALTER TABLE CLOTHINGSIZE MODIFY IsActive BIT NOT NULL;
ALTER TABLE CLOTHINGSIZE ADD CONSTRAINT CK_CLOTHINGSIZE check ( SizeAbbreviation = 'XS' OR SizeAbbreviation = 'S' OR SizeAbbreviation = 'M' OR SizeAbbreviation = 'L' OR SizeAbbreviation = 'XL' OR SizeAbbreviation = 'XXL'  );
ALTER TABLE CLOTHINGSIZE MODIFY IsActive BIT DEFAULT 1;

ALTER TABLE COLOUR ADD CONSTRAINT PK_COLOR PRIMARY KEY (ColourID);
ALTER TABLE COLOUR MODIFY ColourID INTEGER auto_increment;
ALTER TABLE COLOUR MODIFY ColourName VARCHAR (50) not null;
ALTER TABLE COLOUR MODIFY ColourCode char(3) NOT NULL;
ALTER TABLE COLOUR MODIFY ColourCode char(3) unique;
ALTER TABLE COLOUR MODIFY IsActive BIT NOT NULL;
ALTER TABLE COLOUR MODIFY IsActive BIT DEFAULT 1;

ALTER TABLE PRODUCTCATEGORY ADD CONSTRAINT PK_PRODUCTCATEGORY PRIMARY KEY (ProductID, CategoryID);
ALTER TABLE PRODUCTSIZE ADD CONSTRAINT PK_PRODUCTSIZE PRIMARY KEY (ProductID, SizeID);
ALTER TABLE PRODUCTCOLOUR ADD CONSTRAINT PK_PRODUCTCOLOUR PRIMARY KEY (ProductID, ColourID);
