#create database Products_DD;
use Products_DD;
#Name: Charles Pink
#Date: 10/22/2019
#Class: Data Fundamentals

ALTER TABLE PRODUCT ADD CONSTRAINT FK_SupplierID FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID);

ALTER TABLE PRODUCTCATEGORY ADD CONSTRAINT FK_ProductID FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID);

ALTER TABLE PRODUCTSIZE ADD CONSTRAINT FK2_ProductID FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID);
ALTER TABLE PRODUCTCOLOUR ADD CONSTRAINT FK3_ProductID FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID);

ALTER TABLE PRODUCTCOLOUR ADD CONSTRAINT FK_ColourID FOREIGN KEY (ColourID) REFERENCES COLOUR(ColourID);
ALTER TABLE PRODUCTCATEGORY ADD CONSTRAINT FK2_SupplierID FOREIGN KEY (CategoryID) REFERENCES CLOTHINGCATEGORY(CategoryID);
ALTER TABLE PRODUCTSIZE ADD CONSTRAINT FK3_SupplierID FOREIGN KEY (SizeID) REFERENCES CLOTHINGSIZE(SizeID);

